"""Initial migration

Revision ID: a9f0ec31e929
Revises: 
Create Date: 2025-12-17 20:32:18.113965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
"""Initial migration

Revision ID: a9f0ec31e929
...
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel  # <--- ADD THIS LINE HERE


# revision identifiers, used by Alembic.
revision: str = 'a9f0ec31e929'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('sun_sign', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('life_path_number', sa.Integer(), nullable=False),
    sa.Column('hand_element', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dominant_mount', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('heart_line_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
